/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package dino;

import java.awt.Dimension;
import java.awt.FlowLayout;
import java.awt.GridLayout;
import java.awt.Image;
import java.awt.Toolkit;
import java.awt.image.BufferedImage;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;
import javax.imageio.ImageIO;
import javax.swing.ImageIcon;
import javax.swing.JButton;
import javax.swing.JFrame;
import javax.swing.JScrollPane;

/**
 *
 * @author Aratouumea
 */
public class BoardWindow extends javax.swing.JFrame {

    private List<JButton> buttons;
    private List<Boolean> boardFields;
    public BoardWindow() {
        this.setExtendedState(JFrame.MAXIMIZED_BOTH);
        this.setUndecorated(true);  // potem odkomentowac
        initComponents();
        this.setLayout(new FlowLayout(FlowLayout.CENTER));
        initializeBoard();
        setComponentsSize();
        initializeBoardFields();
    }

    public void setComponentsSize() {
        Dimension screenSize = Toolkit.getDefaultToolkit().getScreenSize();
        JScrollPane jsp = new JScrollPane(jPanel1);
        float heightMultiplier = (float) screenSize.getHeight() / Configuration.FRAME_HEIGHT;
        float widthMultiplier = (float) screenSize.getWidth() / Configuration.FRAME_WIDTH;
        jPanel1.setSize(new Dimension(Math.round(Configuration.PANEL_WIDTH + (Configuration.PANEL_WIDTH * widthMultiplier)), Math.round(Configuration.PANEL_HEIGHT + (Configuration.PANEL_HEIGHT * heightMultiplier))));
        jPanel1.setLayout(new GridLayout(8,8,0,0));
        jsp.setSize(new Dimension(Math.round((Configuration.PANEL_WIDTH * widthMultiplier)), Math.round(Configuration.PANEL_HEIGHT + (Configuration.PANEL_HEIGHT * heightMultiplier))));
        this.add(jsp);
        for(JButton button: buttons){
            button.revalidate();
        }
    }

    public void reloadBoardImg() {
        int counter = 0;
        for (JButton button : buttons) {
            try {
                if (boardFields.get(counter) == false) {
                    Image img = ImageIO.read(getClass().getResource("/resources/woda.jpg"));
                    button.setIcon(ImgResizer.resizeImage(img, button.getWidth(), button.getHeight()));
                } else {
                    Image img = ImageIO.read(getClass().getResource("/resources/trawa.jpg"));
                     button.setIcon(ImgResizer.resizeImage(img, button.getWidth(), button.getHeight()));
                }

            } catch (IOException ex) {
            }
            counter++;
        }
    }

    private void initializeBoardFields() {
        boardFields = new ArrayList<>();
        for (int i = 0; i < 64; i++) {
            boardFields.add(false);
        }
        boardFields.set(63, true);
        boardFields.set(55, true);
        boardFields.set(47, true);
        boardFields.set(39, true);
        boardFields.set(31, true);
        boardFields.set(23, true);
        boardFields.set(15, true);
        boardFields.set(7, true);
        boardFields.set(6, true);
        boardFields.set(5, true);

    }

    private void initializeBoard() {

        buttons = new ArrayList<>();
        for (int i = 0; i < Configuration.BOARD_LENGTH; i++) {
            buttons.add(new JButton());
            jPanel1.add(buttons.get(i));
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(640, 640));
        setSize(new java.awt.Dimension(640, 640));

        jPanel1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jPanel1.setPreferredSize(new java.awt.Dimension(700, 650));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 320, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 320, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(72, 72, 72)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 320, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(248, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 320, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 320, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(BoardWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(BoardWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(BoardWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(BoardWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                BoardWindow window = new BoardWindow();
                window.setVisible(true);
                window.reloadBoardImg();

            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
